version: '3'

services:
    wsgi:
        image: elifesciences/profiles:${IMAGE_TAG}
        command: venv/bin/uwsgi --ini=/srv/profiles/uwsgi.ini
        {% if pillar.elife.webserver.app == "caddy" %}
        # when using Caddy, replace any healthcheck with one that uses http
        healthcheck:
            test: ["CMD", "bash", "-c", "curl http://localhost:9000/ping | grep pong"]
        {% endif %}
        volumes:
            - /srv/profiles/app.cfg:/srv/profiles/app.cfg
            - /srv/profiles/clients.yaml:/srv/profiles/clients.yaml
            - /srv/profiles/uwsgi.ini:/srv/profiles/uwsgi.ini
            - /srv/profiles/var/logs:/srv/profiles/var/logs
        networks:
            - default
            - databases
            - sidecars
        ports:
            - 9000:9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - /home/{{ pillar.elife.deploy_user.username }}/profiles/containers.env
        restart: always
    migrate:
        image: elifesciences/profiles:${IMAGE_TAG}
        command: bash -c "/srv/bin/wait_for_port 5432 60 ${POSTGRES_HOST} && venv/bin/python manage.py db upgrade"
        volumes:
            - /srv/profiles/app.cfg:/srv/profiles/app.cfg
            - /srv/profiles/clients.yaml:/srv/profiles/clients.yaml
            - /srv/profiles/var/logs:/srv/profiles/var/logs
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
            - databases
            - sidecars
        env_file:
            - /home/{{ pillar.elife.deploy_user.username }}/profiles/containers.env
    manage:
        image: elifesciences/profiles:${IMAGE_TAG}
        entrypoint: "venv/bin/python manage.py"
        volumes:
            - /srv/profiles/app.cfg:/srv/profiles/app.cfg
            - /srv/profiles/clients.yaml:/srv/profiles/clients.yaml
            - /srv/profiles/var/logs:/srv/profiles/var/logs
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
            - databases
            - sidecars
        env_file:
            - /home/{{ pillar.elife.deploy_user.username }}/profiles/containers.env

networks:
    default:
    databases:
        external: true
    sidecars:
        external: true
