version: '3'

services:
    wsgi:
        image: elifesciences/profiles:${IMAGE_TAG}
        command: venv/bin/newrelic-admin run-program venv/bin/uwsgi --ini=/srv/profiles/uwsgi.ini
        volumes:
            - /srv/profiles/app.cfg:/srv/profiles/app.cfg
            - /srv/profiles/clients.yaml:/srv/profiles/clients.yaml
            - /srv/profiles/uwsgi.ini:/srv/profiles/uwsgi.ini
            - /srv/profiles/var/logs:/srv/profiles/var/logs
        env_file:
            - /home/{{ pillar.elife.deploy_user.username }}/profiles/containers.env
        networks:
            - default
            - sidecars
        ports:
            - 9000:9000
        restart: always

networks:
    default:
    sidecars:
        external: true
