{% for name, details in pillar.profiles.get('oauth_clients', {}).items() %}
{{ name }}:
  client_id: {{ details.client_id }}
  client_secret: {{ details.client_secret }}
  redirect_uris: {{ details.redirect_uris|yaml(False) }}
{% endfor %}
